### ISSUE TITLE
Singularity Hub GET

### ISSUE THREAD

**Issue by vsoch** [miguelcarcamov/container_docker#1]
hey @miguelcarcamov ! 

I noticed that you are performing quite a few number of GETs for your container here (tag HPC in this collection) https://singularity-hub.org/collections/2631 and since we are charged for this, I'd like to suggest that instead of doing actions like:

```
$ singularity exec shub://...
$ singularity run shub://...
```
That you pull the container first, and use that same container for future interactions:

```
$ singularity pull shub://...
$ singularity exec mycontainer.sif
```
Thanks for your help in making sure that Singularity Hub can remain open for everyone!

**Comment by miguelcarcamov** [comment]
Yep, now I am doing pull and exec of the downloaded container after that.

Regards

**Comment by vsoch** [comment]
Great, thank you!

**Comment by miguelcarcamov** [comment]
Hello Vanessa,
The 97k downloads that you were talking about are just from today? Because it does not make sense if just about 100 jobs just call the container like:

singularity pull shub://...

and then 

singularity exec container.simg

Please can you explain me the numbers, in what days, so we can solve the issue?

Thanks!

**Comment by vsoch** [comment]
Hi @miguelcarcamov - the calls of course are not for just one day, but over the month of June (and the few days in July until this morning) The first invoice that gave us concern was for this last month (June 1 through 30). and I was alerted to the usage because our *monthy* allowance was almost depleted in just 2 days. You are correct that if there was just a pull and an exec, we wouldn't see 97K GET requests, but that doesn't seem to be the case. When I turned off the server, your hpc_docker container was in the top (5 I think) of downloaded containers, for the entire history of Singularity Hub. This includes testing containers that have been in testing pipelines for years, and all containers world wide. I'd like to please continue this conversation over the email that we started so that the others are included as well. Thanks!
